'use client';
import { useState, useCallback, useRef } from 'react';
import { supabase } from '@/lib/supabase';
import { normalizeRUT } from '@/lib/utils';
import { FileSpreadsheet, CheckCircle2, AlertCircle, XCircle, Loader2, ChevronDown, Info } from 'lucide-react';
const FIELD_MAP:Record<string,string[]>={rut:['rut','run'],nombre:['nombre','name','first_name'],apellido:['apellido','last_name'],email:['email','correo'],telefono:['telefono','fono','celular'],sueldo_imponible:['sueldo','imponible','salario'],isapre_actual:['isapre','prevision']};
function detectField(h:string){const hn=h.toLowerCase().replace(/[\s-]/g,'_');for(const[f,a]of Object.entries(FIELD_MAP)){if(a.some(x=>hn.includes(x)))return f;}return null;}
function parseCSV(text:string){const lines=text.trim().split(/\r?\n/);if(lines.length<2)return{headers:[] as string[],rows:[] as Record<string,string>[]};const sep=lines[0].includes(';')?';':',';const headers=lines[0].split(sep).map(h=>h.trim().replace(/^"|"$/g,''));const rows=lines.slice(1).map(l=>{const v=l.split(sep).map(x=>x.trim().replace(/^"|"$/g,''));return headers.reduce((o,h,i)=>({...o,[h]:v[i]||''}),{} as Record<string,string>);});return{headers,rows};}
export default function CSVImporter({onComplete}:{onComplete?:(s:{inserted:number;duplicates:number;errors:number;errorRows:string[]})=>void}) {
  const [step,setStep]=useState<'upload'|'mapping'|'importing'|'done'>('upload');
  const [file,setFile]=useState<File|null>(null);
  const [parsed,setParsed]=useState<{headers:string[];rows:Record<string,string>[]}|null>(null);
  const [mapping,setMapping]=useState<Record<string,string>>({});
  const [results,setResults]=useState<{inserted:number;duplicates:number;errors:number;errorRows:string[]}|null>(null);
  const [drag,setDrag]=useState(false);
  const inputRef=useRef<HTMLInputElement>(null);
  const handleFile=useCallback((f:File)=>{setFile(f);const r=new FileReader();r.onload=e=>{const{headers,rows}=parseCSV(e.target?.result as string);const m:Record<string,string>={};headers.forEach(h=>{const field=detectField(h);if(field)m[field]=h;});setParsed({headers,rows});setMapping(m);setStep('mapping');};r.readAsText(f,'UTF-8');},[]);
  const handleImport=async()=>{if(!parsed)return;setStep('importing');const stats={inserted:0,duplicates:0,errors:0,errorRows:[] as string[]};const toInsert=parsed.rows.filter(row=>mapping.rut&&row[mapping.rut]?.trim()).map(row=>{const lead:Record<string,unknown>={};for(const[field,col]of Object.entries(mapping)){if(col&&row[col]!==undefined){let v:unknown=row[col].trim();if(field==='rut')v=normalizeRUT(v as string);if(field==='sueldo_imponible')v=parseFloat((v as string).replace(/[^\d.]/g,''))||null;lead[field]=v||null;}}lead.stage='nuevo';return lead;});for(let i=0;i<toInsert.length;i+=50){const batch=toInsert.slice(i,i+50);const{data,error}=await supabase.from('leads').upsert(batch,{onConflict:'rut',ignoreDuplicates:true}).select('id');if(error){stats.errors+=batch.length;stats.errorRows.push(error.message);}else{stats.inserted+=data?.length||0;stats.duplicates+=batch.length-(data?.length||0);}}setResults(stats);setStep('done');onComplete?.(stats);};
  return (
    <div className="max-w-2xl mx-auto space-y-4">
      {step==='upload'&&(<div onDrop={e=>{e.preventDefault();setDrag(false);const f=e.dataTransfer.files[0];if(f?.name.match(/\.(csv|txt)$/i))handleFile(f);}} onDragOver={e=>{e.preventDefault();setDrag(true);}} onDragLeave={()=>setDrag(false)} onClick={()=>inputRef.current?.click()} className={`border-2 border-dashed rounded-2xl p-14 text-center cursor-pointer transition-all ${drag?'border-blue-400 bg-blue-50':'border-gray-200 hover:border-gray-300'}`}><input ref={inputRef} type="file" accept=".csv,.txt" className="hidden" onChange={e=>{if(e.target.files?.[0])handleFile(e.target.files[0]);}}/><div className="flex flex-col items-center gap-3"><div className="p-4 rounded-2xl bg-gray-100"><FileSpreadsheet size={28} className="text-gray-500"/></div><div><p className="font-semibold text-gray-800">Arrastra tu CSV aquí</p><p className="text-sm text-gray-500 mt-1">o haz clic para seleccionarlo</p></div></div></div>)}
      {step==='mapping'&&parsed&&(<><div className="flex items-center gap-2 p-3 rounded-xl bg-blue-50 border border-blue-200"><Info size={14} className="text-blue-500 shrink-0"/><p className="text-xs text-blue-700"><strong>{parsed.rows.length} filas</strong> en <strong>{file?.name}</strong></p></div><div className="card overflow-hidden"><table className="w-full text-sm"><thead className="bg-gray-50 border-b border-gray-100"><tr><th className="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase">Campo CRM</th><th className="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase">Columna CSV</th></tr></thead><tbody className="divide-y divide-gray-50">{Object.keys(FIELD_MAP).map(field=>(<tr key={field}><td className="px-4 py-2.5 font-medium text-gray-700 capitalize">{field.replace(/_/g,' ')}{field==='rut'&&<span className="text-red-500 ml-1">*</span>}</td><td className="px-4 py-2.5"><div className="relative"><select value={mapping[field]||''} onChange={e=>setMapping(m=>({...m,[field]:e.target.value}))} className="input pr-8 appearance-none"><option value="">— no mapear —</option>{parsed.headers.map(h=><option key={h} value={h}>{h}</option>)}</select><ChevronDown size={12} className="absolute right-2.5 top-1/2 -translate-y-1/2 text-gray-400 pointer-events-none"/></div></td></tr>))}</tbody></table></div><div className="flex justify-end gap-3"><button onClick={()=>setStep('upload')} className="btn-ghost">Cancelar</button><button onClick={handleImport} disabled={!mapping.rut} className="btn-primary disabled:opacity-40">Importar {parsed.rows.length} leads</button></div></>)}
      {step==='importing'&&(<div className="flex flex-col items-center gap-4 py-20"><Loader2 size={32} className="animate-spin text-blue-500"/><p className="text-sm text-gray-600">Importando, no cierres esta ventana...</p></div>)}
      {step==='done'&&results&&(<div className="space-y-4"><div className="grid grid-cols-3 gap-3">{([[CheckCircle2,results.inserted,'Insertados','text-green-500','bg-green-50'],[AlertCircle,results.duplicates,'Duplicados','text-yellow-500','bg-yellow-50'],[XCircle,results.errors,'Errores','text-red-500','bg-red-50']] as const).map(([Icon,val,label,color,bg])=>(<div key={label} className={`${bg} rounded-2xl p-4 text-center`}><Icon size={22} className={`mx-auto mb-1 ${color}`}/><p className="text-2xl font-bold tabular-nums">{val}</p><p className="text-xs text-gray-500">{label}</p></div>))}</div><button onClick={()=>{setStep('upload');setFile(null);setParsed(null);setResults(null);}} className="btn-primary w-full py-3">Importar otro archivo</button></div>)}
    </div>
  );
}